# Generated by Django 3.0 on 2023-05-06 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('oc_lettings_site', '0003_remove_profile_related_name'),
    ]

    operations = [
        migrations.RunSQL("""
        INSERT INTO profiles_profile(
            id,
            favorite_city,
            user_id
        )
        SELECT
            id,
            favorite_city,
            user_id
        FROM
            oc_lettings_site_profile;
    """),
    ]
