# Generated by Django 3.0 on 2023-05-06 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lettings', '0001_initial'),
        ('oc_lettings_site', '0003_remove_profile_related_name'),
    ]

    operations = [
        migrations.RunSQL("""
        INSERT INTO lettings_address(
            id,
            number,
            street,
            city,
            state,
            zip_code,
            country_iso_code
        )
        SELECT
            id,
            number,
            street,
            city,
            state,
            zip_code,
            country_iso_code
        FROM
            oc_lettings_site_address;
    """),
        migrations.RunSQL("""
        INSERT INTO lettings_letting(
            id,
            title,
            address_id
        )
        SELECT
            id,
            title,
            address_id
        FROM
            oc_lettings_site_letting;
        """)
    ]
