version: 2.1

orbs:
  python: circleci/python@2.1.1
  docker: circleci/docker@2.2.0
  azure-acr: circleci/azure-acr@0.2.1

jobs:
  build_and_test:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Linting
          command: python -m flake8
      - run:
          name: Run tests
          command: python -m pytest

workflows:
  main:
    jobs:
      - build_and_test
      - docker/publish:
          image: $DOCKER_PROJECT_USERNAME/$DOCKER_PROJECT_REPONAME
          requires:
            - build_and_test
          filters:
            branches:
              only:
                - master
      - azure-acr/build-and-push-image:
          login-server-name: $AZURE_LOGIN_SERVER_NAME
          registry-name: $AZURE_REGISTRY_NAME
          repo: $AZURE_REPO
          requires:
            - docker/publish
          filters:
            branches:
              only:
                - master
