version: 2.1

orbs:
  python: circleci/python@2.1.1
  docker: circleci/docker@2.2.0
  azure-cli: circleci/azure-cli@1.2.2

jobs:
  build_and_test:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Linting
          command: python -m flake8
      - run:
          name: Run tests
          command: python -m pytest

#  deploy:

workflows:
  main:
    jobs:
      - build_and_test
      - docker/publish:
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
          requires:
            - test_app
          filters:
            branches:
              only:
                - master

